drop_poses:
  bottle:
    pose:
    - 0.169189
    - -0.464252
    - 0.21182199999999998
    - 1.5591200740990545
    - 0.02045525883337354
    - 1.8411129213437782
    xy:
    - 0.169189
    - -0.464252
    frame: flange
    updated_at: '2026-03-18T16:13:46+08:00'
    channel: can0
    robot: nero
  cup:
    pose:
    - 0.244164
    - -0.35546099999999997
    - 0.142872
    - 1.6090364907060923
    - 0.0020245819323134223
    - 2.1079912172662314
    xy:
    - 0.244164
    - -0.35546099999999997
    frame: flange
    updated_at: '2026-03-18T15:50:36+08:00'
    channel: can0
    robot: nero
  drink_can:
    xy:
    - -0.18
    - -0.02
    frame: flange
    updated_at: placeholder
    channel: can0
    robot: nero
  paper:
    xy:
    - -0.08
    - 0.12
    frame: flange
    updated_at: placeholder
    channel: can0
    robot: nero
  cardboard:
    xy:
    - -0.08
    - -0.12
    frame: flange
    updated_at: placeholder
    channel: can0
    robot: nero
  plastic_bag:
    xy:
    - 0.04
    - 0.22
    frame: flange
    updated_at: placeholder
    channel: can0
    robot: nero
  food_waste:
    xy:
    - 0.04
    - 0.02
    frame: flange
    updated_at: placeholder
    channel: can0
    robot: nero
  other_trash:
    xy:
    - 0.04
    - -0.22
    frame: flange
    updated_at: placeholder
    channel: can0
    robot: nero
