drop_poses:
  bottle:
    pose:
    - -0.25814
    - -0.273142
    - 0.230949
    - 1.5451923466681399
    - -0.31264082890974426
    - 0.9252513963597538
    xy:
    - -0.25814
    - -0.273142
    frame: flange
    updated_at: '2026-03-16T16:12:59+08:00'
    channel: can0
    robot: nero
  cup:
    pose:
    - -0.06905399999999999
    - -0.272661
    - 0.236444
    - 1.562087133827445
    - -0.44214425940772356
    - 1.3614615363106968
    xy:
    - -0.06905399999999999
    - -0.272661
    frame: flange
    updated_at: '2026-03-16T20:22:55+08:00'
    channel: can0
    robot: nero
  drink_can:
    xy:
    - -0.18
    - -0.02
    frame: flange
    updated_at: placeholder
    channel: can0
    robot: nero
  paper:
    xy:
    - -0.08
    - 0.12
    frame: flange
    updated_at: placeholder
    channel: can0
    robot: nero
  cardboard:
    xy:
    - -0.08
    - -0.12
    frame: flange
    updated_at: placeholder
    channel: can0
    robot: nero
  plastic_bag:
    xy:
    - 0.04
    - 0.22
    frame: flange
    updated_at: placeholder
    channel: can0
    robot: nero
  food_waste:
    xy:
    - 0.04
    - 0.02
    frame: flange
    updated_at: placeholder
    channel: can0
    robot: nero
  other_trash:
    xy:
    - 0.04
    - -0.22
    frame: flange
    updated_at: placeholder
    channel: can0
    robot: nero
