drop_poses:
  bottle:
    xy:
    - -0.308629
    - -0.37122099999999997
    frame: flange
    updated_at: '2026-03-13T19:18:03+08:00'
    channel: can0
    robot: nero
  cup:
    xy:
    - -0.058509
    - -0.34524
    frame: flange
    updated_at: '2026-03-13T19:18:31+08:00'
    channel: can0
    robot: nero
