model: yolo26s.pt
calibration_file: config/calibration.identity.yaml

camera:
  serial: ""
  width: 1280
  height: 720
  fps: 30
  depth_window_px: 2

workflow:
  target_labels:
    - bottle
    - cup
    - drink_can
  detection_conf: 0.25
  auto_pick: false

robot:
  enabled: true
  channel: can0
  model: nero
  speed_percent: 20
  approach_offset_m: 0.10
  retreat_offset_m: 0.12
  grasp_z_offset_m: 0.015
  pose_rpy_rad:
    - 3.141593
    - 0.0
    - 0.0
  home_pose:
    - 0.300
    - 0.000
    - 0.280
    - 3.141593
    - 0.000000
    - 0.000000

hand:
  enabled: false
  transport: serial
  device_id: 1
  canfd_id: 0
  serial_port: /dev/ttyACM0
  serial_baudrate: 460800
  hand_type: right
  open_angles_rad:
    - 0.20
    - -0.95
    - 0.20
    - -0.03
    - 0.35
    - 0.25
    - 0.03
    - 0.25
    - 0.03
    - 0.20
  close_angles_rad:
    - 0.10
    - -1.25
    - 0.55
    - -0.08
    - 1.05
    - 0.95
    - 0.08
    - 0.95
    - 0.08
    - 0.90
  open_wait_s: 0.4
  close_wait_s: 0.6

classes:
  bottle:
    drop_pose:
      - 0.180
      - -0.220
      - 0.220
      - 3.141593
      - 0.000000
      - 0.000000
  cup:
    drop_pose:
      - 0.180
      - 0.220
      - 0.220
      - 3.141593
      - 0.000000
      - 0.000000
  drink_can:
    drop_pose:
      - 0.220
      - 0.000
      - 0.220
      - 3.141593
      - 0.000000
      - 0.000000
  paper:
    drop_pose:
      - 0.260
      - 0.120
      - 0.220
      - 3.141593
      - 0.000000
      - 0.000000
  cardboard:
    drop_pose:
      - 0.260
      - -0.120
      - 0.220
      - 3.141593
      - 0.000000
      - 0.000000
  plastic_bag:
    drop_pose:
      - 0.120
      - 0.320
      - 0.220
      - 3.141593
      - 0.000000
      - 0.000000
  food_waste:
    drop_pose:
      - 0.120
      - 0.080
      - 0.220
      - 3.141593
      - 0.000000
      - 0.000000
  other_trash:
    drop_pose:
      - 0.120
      - -0.320
      - 0.220
      - 3.141593
      - 0.000000
      - 0.000000
